caterwaul.module( 'terminal' , (function( /* unary , node */e_5p_ZPctQu$PdgvQ9gPBq7DsBh) {return(function($) { (function( ) {var v2plus=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2plus,v2times=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2times,v2minus=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2minus,v2scale=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2scale,v2dot=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2dot,v2norm=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2norm,v2macv=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2macv,v2macs=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2macs,v2unit=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2unit,v2proj=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2proj,v2orth=e_5p_ZPctQu$PdgvQ9gPBq7DsBh.v2orth;
return( (function( ) {var pluralize=function( /* unary , node */f) {;
return function( /* unary , node */xs) {;
return(function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x,f(x) ] ) ) ;
return xr} ) .call(this,xs) ) ) } } ,accessor=function( /* unary , node */name) {;
return function( /* unary , node */x) {;
return arguments.length? (function(it) {return(it[ ( '_' + (name) + '' ) ] =x) ,it} ) .call(this, (this) ) :this[ ( '_' + (name) + '' ) ] } } ,accessors=pluralize(accessor) ,event=function( /* unary , node */name) {;
return function( /* unary , node */x) {;
return x instanceof Function?this.bind(name,x) :this.trigger(name,x) } } ,events=pluralize(event) ;
return($.terminal= {render: (function(it) {return($.merge(it, {black:0,red:1,green:2,yellow:3,blue:4,purple:5,cyan:6,white:7,normal:0,bold:1,italic:3,underline:4,blink:5,negative:7,line: 'K' ,screen: 'J' ,forward:0,backward:1,all:2} ) ) ,it} ) .call(this, ( (function(it) {return($.merge(it.prototype, {add:function( /* unary , node */x) {;
return new this.constructor( (this.xs) .concat( ( [x] ) ) ) } ,toString:function( /* unary , node */) {;
return this.xs.join( '' ) } ,text:function( /* unary , node */x) {;
return this.add(x) } ,clear:function(what,how) {;
return this.add( ( '\033[' + (how) + '' + (what) + '' ) ) } ,at:function(x,y) {;
return this.add(y? ( '\033[' + (Math.round(y) ) + ';' + (Math.round(x) ) + 'H' ) : ( '\033[' + (Math.round(x) ) + 'G' ) ) } ,up:function( /* unary , node */x) {;
return this.add( ( '\033[' + (Math.abs(x) ) + '' + (x<0? "F" : "E" ) + '' ) ) } ,reset:function( /* unary , node */) {;
return this.add( '\033[0;0m' ) } ,down:function( /* unary , node */x) {;
return this.up( -x) } ,bg:function(n,mode) {;
return n!=null?this.add( ( '\033[' + (mode||0) + ';' + (40+n) + 'm' ) ) :this} ,fg:function(n,mode) {;
return n!=null?this.add( ( '\033[' + (mode||0) + ';' + (30+n) + 'm' ) ) :this} } ) ) ,it} ) .call(this, ( (function( ) {var ctor=function( /* unary , node */xs) {;
return this instanceof ctor? (function(it) {return(it.xs=xs) ,it} ) .call(this, (this) ) :new ctor(xs|| [ ] ) } ;
return(ctor) } ) .call(this) ) ) ) ) ,detect_size:function( /* unary , node */) {;
return'\033[s\033[65535;65535H\033[6n\033[u' } ,mouse_mode:function( /* unary , node */on) {;
return( '\033[?1000' + (on? "h" : "l" ) + '' ) } ,overlay_constructor:function( /* unary , node */f) {;
return function() { /* unary ; node */var xs=arguments;
return(function(it) {return(f.apply(it,xs) ) ,it} ) .call(this, ( (function(it) {return(it._visible=true,it._position= [0,0] ,it._dimensions= [0,0] ,it.length=0) ,it} ) .call(this, (this) ) ) ) } } ,overlay_subclass:function( /* unary , node */f) { /* unary ; node */var xs=arguments;
return $.syntax_subclass($.terminal.overlay_constructor( /* unary , node */f) ,$.terminal.overlay_prototype, (function(xs) {var x,x0,xi,xl,xr;
for(var x0= ( { } ) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= ($.merge(x0,x) ) ;
return x0} ) .call(this, (Array.prototype.slice.call( (xs) ) ) .slice(1) ) ) } ,overlay_prototype: (function( ) {var parse_input=function(overlay,s) {;
return(function(it) {return( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (normal_keystrokes(overlay,parse_escape(overlay,x) ) ) ;
return xs} ) .call(this,s.split( '\033[' ) ) ) ,it} ) .call(this, (overlay) ) } ,normal_keystrokes=function(o,s) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (x.charCodeAt(0) <32?control_event(o,x) :key_event(o,x) ) ;
return xs} ) .call(this,s.split( '' ) ) } ,parse_escape=function(o,s) {;
return/^[ABCD]/ .test(s) ? (function(it) {return(s.substr(1) ) } ) .call(this, (arrow_event(o,s.charAt(0) ) ) ) : /^M.../ .test(s) ? (function(it) {return(s.substr(4) ) } ) .call(this, (mouse_event(o,s.substr(1,3) ) ) ) : (function(it) {return(it? (function(it) {return(s.substr(it[0] .length) ) } ) .call(this, (cursor_position(o, +it[2] , +it[1] ) ) ) : (function(it) {return(s.substr(1) ) } ) .call(this, (escaped_key(o,s.charAt(0) ) ) ) ) } ) .call(this, ( /^(\d+);(\d+)R/ .exec(s) ) ) } ,mouse_event=function(o,s) {;
return s.charCodeAt(0) &0x8? (o) .handle( /* unary , node */mouse_event_for(s, 'mouseup' ) ) : (o) .handle( /* unary , node */mouse_event_for(s, 'mousedown' ) ) } ,mouse_event_for=function(s,name) {;
return $.terminal.event[name] (s.charCodeAt(0) &0x7, [s.charCodeAt(1) -32,s.charCodeAt(2) -32] ,s.charCodeAt(0) >>4) } ,arrow_event=function(o,s) {;
return(o) .handle( /* unary , node */$.terminal.event.arrow(s) ) } ,control_event=function(o,s) {;
return(o) .handle( /* unary , node */$.terminal.event.control(s) ) } ,key_event=function(o,s) {;
return(o) .handle( /* unary , node */$.terminal.event.key(s) ) } ,escaped_key=function(o,s) {;
return(o) .handle( /* unary , node */$.terminal.event.escaped(s) ) } ,cursor_position=function(o,x,y) {;
return(function(it) {return( (o) .handle( /* unary , node */$.terminal.event.cursor_position_detect(x,y) ) ) ,it} ) .call(this, ( (o) .cursor_position( /* unary , node */ [x,y] ) ) ) } ;
return($.merge( {bind:function(name,f) {;
return(function(it) {return( (it[ ( '_' + (name) + '_listeners' ) ] =it[ ( '_' + (name) + '_listeners' ) ] || [ ] ) .push(f) ) ,it} ) .call(this, (this) ) } ,trigger:function(name,x) {;
return(function(it) {return(it[ ( '_' + (name) + '_listeners' ) ] && (function(fs) {var f,f0,fi,fl,fr;
for(var fi=0,fl=fs.length;
fi<fl;
 ++fi)f=fs[fi] , (f.call(this,x) ) ;
return fs} ) .call(this,it[ ( '_' + (name) + '_listeners' ) ] ) ) ,it} ) .call(this, (this) ) } ,handle_input:function( /* unary , node */s) {;
return parse_input(this,s) } ,contains:function(x,y) {;
return x instanceof Array?this.contains(x[0] ,x[1] ) :x>=this._position[0] &&x<=this._position[0] +this._dimensions[0] &&y>=this._position[1] &&y<=this._position[1] +this._dimensions[1] } ,handle:function( /* unary , node */event) {;
return(function(it) {return(this.trigger(event.name() ,event) ) ,it} ) .call(this, ( (function(it) {return(this.propagate( /* unary , node */event) ) ,it} ) .call(this, ( (function(it) {return(this.trigger( ( '' + (event.name() ) + '_capture' ) ,event) ) ,it} ) .call(this, ( ( ! (event.position() ) && (event.position(this.cursor_position() ) ) ) ) ) ) ) ) ) } ,propagate:function( /* unary , node */event) {;
return(function( ) {var translated= (event) .visit( /* unary , node */this) ;
return( (function(it) {return( ( ! (it.length) && (event.destination_is(this) ) ) ) ,it} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .handle( /* unary , node */translated) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length,x0;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .contains( /* unary , node */translated.position() ) ) &&xr.push(x) ;
return xr} ) .call(this,Array.prototype.slice.call( (this) ) ) ) ) ) ) } ) .call(this) } ,children:function() { /* unary ; node */var xs=arguments;
return(function(it) {return(this) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (this.push) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (x.render? [x] :x) ) ) ;
return xr} ) .call(this,Array.prototype.slice.call( (xs) ) ) ) ) ) } ,render_root:function( /* unary , node */) {;
return this.render( /* unary , node */ {position: [1,1] ,parent:null} ) } ,render:function( /* unary , node */context) {;
return this._visible? (function( ) {var p=v2plus(this._position,context.position) ;
return(this.content(context) + (function(it) {return(it.join( '' ) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.render( /* unary , node */ {parent:this,position:p} ) ) ) ;
return xr} ) .call(this,Array.prototype.slice.call( (this) ) ) ) ) ) } ) .call(this) : '' } ,serialize:function( /* unary , node */xs) {;
return(function(it) {return(it.push( ( '[overlay @[' + (this._position.join( ", " ) ) + ']: ' ) ) , (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .serialize( /* unary , node */it) ) ;
return xs} ) .call(this,Array.prototype.slice.call( (this) ) ) ,it.push( ']' ) ) ,it} ) .call(this, (xs) ) } } ,events( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( ( [x, ( '' + (x) + '_capture' ) ] ) ) ) ;
return xr} ) .call(this, [ 'click' , 'doubleclick' , 'mousedown' , 'mouseup' , 'key' , 'control' , 'cursor_position_detect' ] ) ) ,accessors( [ 'visible' , 'position' , 'dimensions' , 'parent' , 'cursor_position' ] ) ) ) } ) .call(this) ,event: (function( ) {var arrow_codes= {A: 'n' ,B: 's' ,C: 'e' ,D: 'w' } ;
return( (function(it) {return($.merge(it, {mousedown:function(button,position,keys) {;
return $.terminal.event( {_name: 'mousedown' ,_button:button,_position:position,_modifiers:keys} ) } ,mouseup:function(button,position,keys) {;
return $.terminal.event( {_name: 'mouseup' ,_button:button,_position:position,_modifiers:keys} ) } ,click:function(button,position,keys) {;
return $.terminal.event( {_name: 'click' ,_button:button,_position:position,_modifiers:keys} ) } ,doubleclick:function(button,position,keys) {;
return $.terminal.event( {_name: 'doubleclick' ,_button:button,_position:position,_modifiers:keys} ) } ,key:function( /* unary , node */character) {;
return $.terminal.event( {_name: 'key' ,_key:character} ) } ,escaped:function( /* unary , node */character) {;
return $.terminal.event( {_name: 'key' ,_key:character,_modifiers:0x2} ) } ,arrow:function( /* unary , node */code) {;
return $.terminal.event( {_name: 'control' ,_arrow:arrow_codes[code] } ) } ,control:function( /* unary , node */character) {;
return $.terminal.event( {_name: 'control' ,_code:character} ) } ,cursor_position_detect:function(x,y) {;
return $.terminal.event( {_name: 'cursor_position_detect' ,_position: [x,y] } ) } ,shift:1,meta:2,ctrl:4,button1:1,button2:2,button3:4} ) ) ,it} ) .call(this, ( (function(it) {return($.merge(it.prototype, {stop:function( /* unary , node */) {;
return this._stopped=this} ,target:function( /* unary , node */) {;
return this._target} ,path:function( /* unary , node */) {;
return this._path} ,position:function( /* unary , node */) {;
return this._position|| [0,0] } ,destination_is:function( /* unary , node */o) {;
return(function(it) {return(this) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .target( /* unary , node */o) ) ;
return xs} ) .call(this,this._path) ) ) } ,visit:function( /* unary , node */overlay) {;
return(function(it) {return(this.path() .push(it) ) ,it} ) .call(this, (new this.constructor($.merge( { } ,this.data, {_position:v2minus(this.position() ,overlay.position() ) } ) ,this._target) ) ) } } ,accessors( [ 'name' , 'code' , 'button' , 'arrow' , 'key' , 'modifiers' ] ) ) ) ,it} ) .call(this, ( (function(data,target) {return this instanceof $.terminal.event? (function(it) {return($.merge(it,data) ,it._target=target||null,it._path= [ ] ) ,it} ) .call(this, (this) ) :new $.terminal.event(data,target) } ) ) ) ) ) ) } ) .call(this) } ,$.merge($.terminal, {linear_text_overlay: (function( ) {var ctor=function(text,options) {;
return text instanceof this.constructor? (function(it) {return(it._text=text._text,it._fg=text._fg,it._bg=text._bg) ,it} ) .call(this, (this) ) : (function(it) {return( ( (options) && (it._fg=options.fg,it._bg=options.bg) ) ) ,it} ) .call(this, ( (function(it) {return(it._text=text) ,it} ) .call(this, (this) ) ) ) } ,methods= {content:function( /* unary , node */context) {;
return this.renderer_for(context) .text(this._text) } ,renderer_for:function( /* unary , node */c) {;
return(function( ) {var p=v2plus(this._position,c.position) ;
return($.terminal.render() .at(p[0] ,p[1] ) .fg(this._fg) .bg(this._bg) ) } ) .call(this) } } ;
return($.terminal.overlay_subclass(ctor,accessors( [ 'text' , 'fg' , 'bg' ] ) ,methods) ) } ) .call(this) ,container_overlay: (function( ) {var ctor=function() { /* unary ; node */var xs=arguments;
return this.children.apply(this,xs) } ,methods= { /* unary , node */content:function( /* unary , node */context) {;
return'' } } ;
return($.terminal.overlay_subclass(ctor,methods) ) } ) .call(this) ,masking_overlay: (function( ) {var ctor=function( /* unary , node */content_cc) {;
return(function(it) {return(it._content_cc=content_cc) ,it} ) .call(this, (this) ) } ,methods= { /* unary , node */content:function( /* unary , node */context) {;
return(function( ) {var p1=context.position,p2=v2plus(p1,context.parent._dimensions) ,row=function( /* unary , node */y) {;
return this._content_cc? (function(it) {return(it.join( '' ) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (this._content_cc(x,y) ) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (p1[0] ) , (p2[0] ) , (1) ) ) ) ) : (function(it) {return(it.join( '' ) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( ' ' ) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (p1[0] ) , (p2[0] ) , (1) ) ) ) ) } ;
return( (function(it) {return(it.join( '' ) ) } ) .call(this, ( (function(ys) {var y,y0,yi,yl,yr;
for(var yr=new ys.constructor() ,yi=0,yl=ys.length;
yi<yl;
 ++yi)y=ys[yi] ,yr.push( ($.terminal.render() .at(p1[0] ,y) .text(row( /* unary , node */y) ) ) ) ;
return yr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (p1[1] ) , (p2[1] ) , (1) ) ) ) ) ) } ) .call(this) } } ;
return($.terminal.overlay_subclass(ctor,accessors( [ /* unary , node */ 'content_cc' ] ) ,methods) ) } ) .call(this) ,toplevel_overlay: (function( ) {var ctor=function( /* unary , node */stdout_cc) {;
return(function(it) {return(it.cursor_position_detect_capture( (function(t,f) {return(function( ) {return f.apply(t,arguments) } ) } ) (this, (function(x) {return it.record_size(x) } ) ) ) ) ,it} ) .call(this, ( (function(it) {return(it._stdout_cc=stdout_cc,it._sizing=false,it._dimensions= [0,0] ) ,it} ) .call(this, (this) ) ) ) } ,methods= {update_size:function( /* unary , node */) {;
return(function(it) {return(it._sizing=true,it._stdout_cc( /* unary , node */$.terminal.detect_size() ) ) ,it} ) .call(this, (this) ) } ,record_size:function( /* unary , node */e) {;
return( (this._sizing) && ( (function(it) {return(it._sizing=false) ,it} ) .call(this, (this.dimensions(e.position() ) ) ) ) ) } ,mouse_mode:function( /* unary , node */on) {;
return(function(it) {return(it._stdout_cc( /* unary , node */$.terminal.mouse_mode(on) ) ) ,it} ) .call(this, (this) ) } ,content:function( /* unary , node */context) {;
return'' } ,repaint:function( /* unary , node */) {;
return(function(it) {return(it._stdout_cc( /* unary , node */it.render_root() ) ) ,it} ) .call(this, (this) ) } } ;
return($.terminal.overlay_subclass(ctor,accessors( [ 'dimensions' , 'stdout_cc' ] ) ,methods) ) } ) .call(this) } ) ) } ) .call(this) ) } ) .call(this) } ) } ) .call(this, /* unary , node */caterwaul.linear.vector(2, 'v2' ) ) ) ;
